spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    drop-first: false

user-service:
  url: http://localhost:8001/api/users

resilience4j:
  circuitbreaker:
    instances:
      userClient:
        registerHealthIndicator: true
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.innowise.orderservice.client: DEBUG

